apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsdesk.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsdesk.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsdesk.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opsdesk.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
